# Generated by Django 5.2.1 on 2025-05-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
