# Generated by Django 5.2.1 on 2025-05-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userdb_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeName', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('RecipeImage', models.ImageField(blank=True, default='recipe_images/b170870007dfa419295d949814474ab2_t.jpg', null=True, upload_to='recipe_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='pages.userdb')),
            ],
        ),
    ]
