# Generated by Django 5.2.1 on 2025-05-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_recipe_recipedb_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientDB',
        ),
    ]
